### ISSUE TITLE
Missing Snap Arm64

### ISSUE THREAD

**Issue by MoriGM** [coldfix/certbot-dns-netcup#21]
Installation via Arm64 is not possible

https://snapcraft.io/docs/architectures

**Comment by coldfix** [comment]
Hi,
thanks for the input! As far as I understand, adding:

```yml
    architectures:
      - build-on: amd64
        run-on: all
```

should be enough to address. New snap
